// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2KnqNw5cVFxDYl3yz4zZzcNq9mAz2Smw',
    appId: '1:895989706867:web:a4128d2fb42f1b02d2ba06',
    messagingSenderId: '895989706867',
    projectId: 'church-f4056',
    authDomain: 'church-f4056.firebaseapp.com',
    storageBucket: 'church-f4056.appspot.com',
    measurementId: 'G-FZKHE6W6Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqTTzKvzjqJ_AIcCk9ywDcjZflI_GYts',
    appId: '1:895989706867:android:2b25519094e27c2ad2ba06',
    messagingSenderId: '895989706867',
    projectId: 'church-f4056',
    storageBucket: 'church-f4056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUisA2Dil8-0Fvpyrl0Q8VLN14BFEU55s',
    appId: '1:895989706867:ios:ec65e0385968644dd2ba06',
    messagingSenderId: '895989706867',
    projectId: 'church-f4056',
    storageBucket: 'church-f4056.appspot.com',
    iosClientId: '895989706867-ogut7o254m2ipo8r82egmgr5oehkshek.apps.googleusercontent.com',
    iosBundleId: 'com.oliver.chruch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUisA2Dil8-0Fvpyrl0Q8VLN14BFEU55s',
    appId: '1:895989706867:ios:ec65e0385968644dd2ba06',
    messagingSenderId: '895989706867',
    projectId: 'church-f4056',
    storageBucket: 'church-f4056.appspot.com',
    iosClientId: '895989706867-ogut7o254m2ipo8r82egmgr5oehkshek.apps.googleusercontent.com',
    iosBundleId: 'com.oliver.chruch',
  );
}
